version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database_name
      POSTGRES_USER: my_database_user
      POSTGRES_PASSWORD: my_database_password
    ports:
      - "5432:5432"
